### PR TITLE
Allow setting working directory for pandoc process

### PR DESCRIPTION
**Pull request by cheryllium**
This PR adds the option to specify the working directory for the pandoc process. Like so:

```php
(new Pandoc\Pandoc)->workDir($directory_path_here)->from(... // and so on...
```

This was prompted by a permissions issue I ran into in my particular use case - which could be solved by changing the working directory to one where the user running this process has guaranteed permissions.

Thanks for your work on this great library.

### CODE REVIEW

**Comment by hanspagel** [comment]
Thanks for the PR! Would you mind to change it to `->workingDirectory()`? And 💖 if you could add a small note to the README.

**Comment by cheryllium** [comment]
@hanspagel I can, but the reason I named it `workDir()` is to be consistent with the naming format of `dataDir()`. I don't have a preference either way, but if we change it to `workingDirectory()`, I think the other method should also be renamed (to `dataDirectory()`) to keep it consistent. What do you think?

**Comment by hanspagel** [comment]
Ah, you’re right!

It’s called `--data-dir` in Pandoc, but `workingDirectory` in the symfony package. 🤔

Maybe `->cwd()` then? 😅 It’s common and doesn’t conflict with the Pandoc naming scheme.

**Comment by cheryllium** [comment]
I see what you mean! Yeah, I agree then, better to keep `dataDir()` similar to the Pandoc option, so that it's intuitive to those familiar with Pandoc. We don't have to mirror Symfony's naming scheme though, as that's inside the black box. I think `cwd()` is perfect, good thinking! I'll make that change :)

**Comment by hanspagel** [comment]
Thanks @cheryllium! 💖

**Pull request merged**
