### PR TITLE
Add option to set custom options

### PR DESCRIPTION
**Pull request by cheryllium**
For #15

### CODE REVIEW

**Comment by cheryllium** [comment]
@hanspagel ready for your review :)

**Comment by maggie0002** [comment]
Hi @cheryllium,

I may try giving this a whirl next week. Would be great if you could include a commit updating the docs on its use. 

Thanks for taking this on.

**Comment by maggie0002** [comment]
I also see some of the options deemed common are in their own function. Do you see these as common? I note they are the same as from my post. I merely picked three random examples, I think the approach to be able to pass options more broadly like your first commit makes most sense. Not sure if the third commit is necessary, just wanted to flag that in case it was the result of my post.

**Comment by cheryllium** [comment]
@maggie0002 Yeah, I thought those were what you needed specifically, so that's why I added shortcuts for them.

I'd agree with reverting it then. @hanspagel do you want to weigh in?

I think wrappers around the generic function, like those, are nice to have but we probably want a better idea of which options would be most useful to have wrappers for first. I don't have any suggestions. 

I'll add proper docs. Thanks for the reminder and other good thoughts!

**Comment by hanspagel** [comment]
Thanks for your work on this! 🙌 I’ve merged it, fixed a minor mistake, added documentation and tagged a new version. ✌️

**Pull request merged**
